### Register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "Budi Investor Test User",
  "email": "testbudi@investor.com",
  "password": "password123"
}

### Register With Referrer
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "Ari Setiawan Test User",
  "email": "testari@investor.com",
  "password": "password123",
  "referrerCode": "<referral_code_from_referrer>"
}

### Login User (Investor)
POST http://localhost:3000/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "testbudi@investor.com",
  "password": "password123"
}