### Register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "Budi Investor",
  "email": "budi@investor.com",
  "password": "password123"
}

### Register With Referrer
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "Ari Setiawan asdf",
  "email": "arikeren232ds@investor.com",
  "password": "passdfasdfasdfasd2",
  "referrerCode": "d156f5bf-c03c-451c-8e66-4d8e8fcda464"
}